config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :reservations, only: [:new, :create, :destroy] do
    get :search, on: :collection
  end

  root to: redirect('/rooms')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room

  validates :start_date, :end_date, :guest_name, :number_of_guests, presence: true
  validates :number_of_guests, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
  validate :start_date_is_before_end_date
  validate :already_reserved
  validate :room_with_insufficient_capacity

  scope :of_the_week, -> { where.not('start_date > ? OR end_date < ?', Date.tomorrow + 7.days, Date.tomorrow) }
  scope :of_the_month, -> { where.not('start_date > ? OR end_date < ?', Date.tomorrow + 30.days, Date.tomorrow) }
  

  def duration
    if start_date.present? && end_date.present? && end_date > start_date
      (end_date - start_date).to_i
    end
  end

  def remaing_days_until_custom_date(custom_date)
    if start_date.present? && end_date.present? && end_date > start_date
      if Date.tomorrow > end_date
        0
      elsif Date.tomorrow < start_date
        if custom_date <= end_date
          (custom_date - start_date).to_i
        else
          (end_date - start_date).to_i
        end
      else
        if custom_date <= end_date
          (custom_date - start_date).to_i - (Date.tomorrow - start_date).to_i
        else
          (end_date - start_date + 1).to_i - (Date.tomorrow - start_date).to_i
        end
      end
    end
  end

  def code
    if id.present? && room&.code.present?
      formatted_id = '%02d' % id
      "#{room.code}-#{formatted_id}"
    end
  end

  private

  def already_reserved
    if start_date.present? && end_date.present? && room_id.present?
      if (Reservation.where("room_id = ? AND start_date < ? AND end_date > ?", room_id, end_date, start_date)).any?
        errors.add(:base, :invalid_dates, message: 'The room is already reserved on these dates')
      end
    end
  end

  def room_with_insufficient_capacity
    if room_id.present? && number_of_guests.present? && Room.find(room_id).capacity < number_of_guests
      errors.add(:base, :invalid_number_of_guests, message: 'The selected room does not have enough capacity')
    end
  end

  def start_date_is_before_end_date
    if start_date.present? && end_date.present? && start_date >= end_date
      errors.add(:base, :invalid_dates, message: 'The start date should be before the end date')
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations, dependent: :destroy

  validates :code, :capacity, presence: true
  validates :code, uniqueness: true
  validates :capacity, numericality: { greater_than: 0, less_than_or_equal_to: 10 }

  scope :with_capacity, ->(number_of_guests) { where('capacity >= ?', number_of_guests) }
  scope :not_available, ->(start_date, end_date) { joins(:reservations).where('start_date < ? AND end_date > ?', end_date, start_date) }
end

app/controllers/application_controller.rb
require 'will_paginate/array'

class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def search
    @should_show_results = params.dig(:reservation, :start_date).present? &&
      params.dig(:reservation, :end_date).present? &&
      params.dig(:reservation, :number_of_guests).present? &&
      params.dig(:reservation, :end_date) > params.dig(:reservation, :start_date)
    if @should_show_results
      @not_available_rooms = Room.not_available(params.dig(:reservation, :start_date), params.dig(:reservation, :end_date))
      @available_rooms = Room.with_capacity(params.dig(:reservation, :number_of_guests)) - @not_available_rooms
      @available_rooms = @available_rooms.paginate(page: params[:page])
    else
      @available_rooms = Room.none.paginate(page: params[:page])
    end
  end

  def new
    @reservation = Reservation.new(reservation_params)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to @reservation.room,
        notice: "Reservation #{@reservation.code} was successfully created."
    else
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to room_path(@reservation.room),
      notice: "Reservation #{@reservation.code} was successfully destroyed."
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date, :number_of_guests, :guest_name, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all.paginate(page: params[:page])
    if @rooms.any?
      @occupations_per_room_on_week = {}
      @grouped_reservations_on_week = Reservation.of_the_week.group_by { |r| r.room_id }
      @grouped_reservations_on_week.each do |reservations|
        @occupations_per_room_on_week[reservations[0]] = get_percentage_of_reserved_days(reservations[1], 7)
      end

      @occupations_per_room_on_month = {}
      @grouped_reservations_on_month = Reservation.of_the_month.group_by { |r| r.room_id }
      @grouped_reservations_on_month.each do |reservations|
        @occupations_per_room_on_month[reservations[0]] = get_percentage_of_reserved_days(reservations[1], 30)
      end

      @global_week_occupation = average_sum_of_reserved_days(@occupations_per_room_on_week, @rooms.count)
      @global_month_occupation = average_sum_of_reserved_days(@occupations_per_room_on_month, @rooms.count)
    end
  end

  def show
    reservations_of_the_week = Reservation.of_the_week.where(room: @room)
    @room_week_occupation = get_percentage_of_reserved_days(reservations_of_the_week, 7)

    reservations_of_the_month = Reservation.of_the_month.where(room: @room)
    @room_month_occupation = get_percentage_of_reserved_days(reservations_of_the_month, 30)

    @reservations = @room.reservations.paginate(page: params[:page])
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
    def average_sum_of_reserved_days(occupations_per_room, rooms_count)
      occupations_per_room.map { |occupation| occupation[1] }.inject(0, :+) / rooms_count
    end

    def get_percentage_of_reserved_days(reservations, days_limit)
      reservations.map { |reservation| reservation.remaing_days_until_custom_date(Date.tomorrow + days_limit.days) }.inject(0, :+) / days_limit.to_f * 100
    end

    def room_params
      params.require(:room).permit(:code, :capacity, :notes)
    end

    def set_room
      @room = Room.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guava Inn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1>Guava Inn</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/new.html.erb
<h2>New Reservation</h2>

<%= simple_form_for(@reservation) do |f| %>
  <%= render "shared/error_messages", resource: @reservation %>

  <div class="form-inputs">
    <%= f.input :start_date, html5: true, input_html: {value: params[:reservation][:start_date]} %>
    <br/>
    <%= f.input :end_date, html5: true, input_html: {value: params[:reservation][:end_date]} %>
    <br/>
    <%= f.input :number_of_guests, as: :select, collection: 1..10, selected: params[:reservation][:number_of_guests] %>
    <br/>
    <%= f.input :room_id, as: :select, collection: Room.all.map { |room| [room.code, room.id] } %>
    <br/>
    <%= f.input :guest_name %>
  </div>

  <br/>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', :back %>

app/views/reservations/search.html.erb
<h2>New Reservation</h2>


<%= simple_form_for(Reservation.new, url: search_reservations_path, method: :get) do |f| %>
  <div class="field">
    <%= f.input :start_date, html5: true, label: 'From', input_html: {value: params.dig(:reservation, :start_date) || Date.today} %>
    <br/>
    <%= f.input :end_date, html5: true, label: 'To', input_html: {value: params.dig(:reservation, :end_date) || Date.tomorrow} %>
    <br/>
    <%= f.input :number_of_guests, as: :select, collection: 1..10, label: '# of guests', selected: params.dig(:reservation, :number_of_guests) || 1 %>
  </div>

  <div class="actions">
    <%= submit_tag 'Search for Available Rooms' %>
  </div>
<% end %>

<% if @should_show_results %>
  <section class="listing">
    <h3>Available Rooms</h3>

    <table>
      <thead>
        <tr>
          <th>Code</th>
          <th>Capacity</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @available_rooms.any? %>
          <% @available_rooms.each do |room| %>
            <tr>
              <td><%= room.code %></td>
              <td><%= pluralize(room.capacity, 'person', 'people') %></td>
              <td>
                <%= link_to 'Create Reservation', new_reservation_path( reservation: {
                  room_id: room.id,
                  start_date: params.dig(:reservation, :start_date),
                  end_date: params.dig(:reservation, :end_date),
                  number_of_guests: params.dig(:reservation, :number_of_guests),
                }) %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="7">There are no available rooms for the selected filters.</td>
        <% end %>
      </tbody>
    </table>
  </section>
<% end %>

<br/>
<%= will_paginate @available_rooms %>
<br/>

<%= link_to 'Back', root_path %>

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= render "shared/error_messages", resource: @room %>

  <div class="form-inputs">
    <%= f.input :code %>
    <br/>
    <%= f.input :capacity, as: :select, collection: 1..10, default: 1 %>
    <br/>
    <%= f.input :notes %>
  </div>

  <br/>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h2>Editing Room</h2>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<section class="global-occupation">
  <h2>Global Occupation</h2>
  <div class="global-occupation-box">
    <h3>Week</h3>
    <span class="global-occupation-rate">
      <% if @global_week_occupation.present? %>
        <%= @global_week_occupation.round(2) %>%
      <% else %>
        0%
      <% end %>
    </span><br/>
    <small>in the next 7 days</small>
  </div>
  <div class="global-occupation-box">
    <h3>Month</h3>
    <span class="global-occupation-rate">
      <% if @global_month_occupation.present? %>
        <%= @global_month_occupation.round(2) %>%
      <% else %>
        0%
      <% end %>
    </span><br/>
    <small>in the next 30 days</small>
  </div>
</section>

<section class="listing">
  <h2>Rooms</h2>

  <table>
    <thead>
      <tr>
        <th>Code</th>
        <th>Capacity</th>
        <th colspan="2" width="30%">Occupation (Week / Month)</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% if @rooms.any? %>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.code %></td>
            <td><%= pluralize(room.capacity, 'person', 'people') %></td>
              <% if @occupations_per_room_on_week[room.id].present? %>
                <td><%= @occupations_per_room_on_week[room.id].round(2) %>%</td>
              <% else %>
                <td>0%</td>
              <% end %>
              <% if @occupations_per_room_on_month[room.id].present? %>
                <td><%= @occupations_per_room_on_month[room.id].round(2) %>%</td>
              <% else %>
                <td>0%</td>
              <% end %>
            <td><%= link_to 'Show', room %></td>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% else %>
        <td colspan="7">There are no rooms in the Guava Inn yet.</td>
      <% end %>
    </tbody>
  </table>
</section>

<br/>
<%= will_paginate @rooms %>
<br/>

<%= link_to 'New Reservation', search_reservations_path %> |
<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h2>New Room</h2>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/reservations/new.html.erb
New Reservation from Room

app/views/rooms/show.html.erb
<h2>Room <%= @room.code %></h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @room.code %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Occupation Rate (Week):</strong>
  <% if @room_week_occupation.present? %>
    <%= @room_week_occupation.round(2) %>%
  <% else %>
    0%
  <% end %>
</p>

<p>
  <strong>Occupation Rate (Month):</strong>
  <% if @room_month_occupation.present? %>
    <%= @room_month_occupation.round(2) %>%
  <% else %>
    0%
  <% end %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @room.notes %>
</p>

<h3>Reservations</h3>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Period</th>
      <th>Duration</th>
      <th width="30%">Guest Name</th>
      <th># of guests</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @reservations.any? %>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.code %></td>
          <td><%= l reservation.start_date %> to <%= l reservation.end_date %></td>
          <td><%= pluralize(reservation.duration, 'night') %></td>
          <td><%= reservation.guest_name %></td>
          <td><%= pluralize(reservation.number_of_guests, 'guest') %></td>
          <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6">
          There are no reservations for this room yet.
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<%= will_paginate @reservations %>
<br/>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
  <div class="alert-container">
    <div class="alert alert-top alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= t(:default_message, scope: 'simple_form.error_notification') %><br/>
      <% resource.errors.full_messages.each do |msg| %>
        <%= msg.sub(resource.class.name, '') %><br/>
      <% end %>
    </div>
  </div>
<% end %>